### ISSUE TITLE
Download the model from server.

### ISSUE THREAD

**Issue by ibei** [mccorby/PhotoLabeller#8]
so far I can upload the updates in client to the server.
the main process is:
first i save a model.zip locally and open the app,
take some pics and click the "training" botton,
then it goes to the training interface,
after certain iters, the training is finished, and the server can get the updates uploaded by the clients.
So the path from client to server is working.
what i wanna know is how to download the model from the server?
Any suggesstion is appreciated!

**Comment by ibei** [comment]
it seems that when the updates uploaded reach one certain number, the training on server begins. and then push the new model to the client. 
is this right? but after i modify the property.file to set the min_updates to make sure the number of uploaded updates  is reached, nothing is generated.  neither the model nor the log.
Any suggerstions?

**Comment by JieZhou0805** [comment]
Where can I download model.zip? Thanks in advance for your answer.

**Comment by JieZhou0805** [comment]
Where can I download model.zip? Thanks in advance for your answer.

**Comment by ibei** [comment]
> Where can I download model.zip? Thanks in advance for your answer.
this is the initial model, which you can train by yourself

**Comment by JieZhou0805** [comment]
I found model.zip in the client code, but my server cannot get the updates uploaded by the clients. Should I save modelzip to my phone in advance? If so, in what path? Thanks in advance for your answer.

> > Where can I download model.zip? Thanks in advance for your answer.
> > this is the initial model, which you can train by yourself

**Comment by mccorby** [comment]
Sorry but I don't maintain this project anymore apart from small updates from time to time.
The model going to the server should go as a stream of bytes so you don't need to save it anywhere.

Check that the server is actually ready to receive them.
